import { Router, Response } from 'express';
import { requireAuth } from '../middleware/auth';
import { validateBody } from '../middleware/validation';
import { RequestWithUser, logger } from '../middleware/logging';
import { generate } from '../ai/vertex-client';
import { buildIncidentExtractionPrompt } from '../ai/prompt-builder';
import { parseAndValidate } from '../ai/schema-validator';
import {
  INCIDENT_EXTRACTION_SCHEMA,
  EXTRACT_INCIDENT_REQUEST_SCHEMA,
} from '../schemas/incident-extraction';
import { hasSafetyKeyword } from '../policies/safety';
import { config } from '../config';

const router = Router();

/**
 * POST /api/v1/extract-incident
 *
 * Extracts structured incident fields from a voice note transcript.
 * Expects the transcript to have already been generated by Speech-to-Text.
 *
 * Body: { voiceNoteId, profileId, audioStoragePath, personaTypeKey? }
 * Returns: { incident: IncidentExtraction, safetyFlag: boolean }
 */
router.post(
  '/extract-incident',
  requireAuth,
  validateBody(EXTRACT_INCIDENT_REQUEST_SCHEMA),
  async (req: RequestWithUser, res: Response) => {
    const { voiceNoteId, profileId, personaTypeKey } = req.body;
    // audioStoragePath is used by the STT step (handled by Cloud Functions for now)

    logger.info({
      message: 'extract-incident request',
      uid: req.uid,
      voiceNoteId,
      profileId,
    });

    try {
      // In the full implementation, this endpoint would:
      // 1. Download audio from Firebase Storage
      // 2. Run Google Cloud STT to get transcript
      // 3. Run Gemma 4 incident extraction on the transcript
      //
      // For now, the transcript must be provided in the request body
      // (the Cloud Functions handle the full STT pipeline).
      const transcript: string = req.body.transcript ?? '';

      if (!transcript) {
        res.status(400).json({ error: 'transcript is required for incident extraction.' });
        return;
      }

      const safetyFlagFromKeywords = hasSafetyKeyword(transcript);

      const prompt = buildIncidentExtractionPrompt({ transcript, personaTypeKey });

      const rawText = await generate({
        prompt,
        model: config.models.default,
        maxTokens: 512,
        temperature: 0.2,
        responseSchema: INCIDENT_EXTRACTION_SCHEMA,
      });

      const incident = parseAndValidate(rawText, INCIDENT_EXTRACTION_SCHEMA, 'extract-incident');
      const safetyFlag =
        (incident as { safetyFlag?: boolean }).safetyFlag === true || safetyFlagFromKeywords;

      res.json({ success: true, incident, safetyFlag, voiceNoteId });
    } catch (err) {
      logger.error({ message: 'extract-incident failed', uid: req.uid, error: String(err) });
      res.status(500).json({ error: 'Failed to extract incident. Please try again.' });
    }
  }
);

export default router;
